/*++

Copyright (C) 2025 Autodesk Inc.

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the Autodesk Inc. nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS' AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL AUTODESK INC. BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


This file has been generated by the Automatic Component Toolkit (ACT) version 1.8.0-develop.

Abstract: This is an autogenerated C++ header file in order to allow easy
development of MC Driver for the OpenFOAM CFD Solver. The implementer of MC Driver for the OpenFOAM CFD Solver needs to
derive concrete classes from the abstract classes in this header.

Interface version: 2.0.0

*/


#ifndef __LIBMCDRIVER_OPENFOAM_CPPINTERFACES
#define __LIBMCDRIVER_OPENFOAM_CPPINTERFACES

#include <string>
#include <memory>

#include "libmcdriver_openfoam_types.hpp"


#include "libmcenv_dynamic.hpp"

namespace LibMCDriver_OpenFOAM {
namespace Impl {

/**
 Forward declarations of class interfaces
*/
class IBase;
class IDriver;
class IOpenFOAMCase;
class IDriver_OpenFOAM;



/*************************************************************************************************************************
 Parameter Cache definitions
**************************************************************************************************************************/

class ParameterCache {
	public:
		virtual ~ParameterCache() {}
};

template <class T1> class ParameterCache_1 : public ParameterCache {
	private:
		T1 m_param1;
	public:
		ParameterCache_1 (const T1 & param1)
			: m_param1 (param1)
		{
		}

		void retrieveData (T1 & param1)
		{
			param1 = m_param1;
		}
};

template <class T1, class T2> class ParameterCache_2 : public ParameterCache {
	private:
		T1 m_param1;
		T2 m_param2;
	public:
		ParameterCache_2 (const T1 & param1, const T2 & param2)
			: m_param1 (param1), m_param2 (param2)
		{
		}

		void retrieveData (T1 & param1, T2 & param2)
		{
			param1 = m_param1;
			param2 = m_param2;
		}
};

template <class T1, class T2, class T3> class ParameterCache_3 : public ParameterCache {
	private:
		T1 m_param1;
		T2 m_param2;
		T3 m_param3;
	public:
		ParameterCache_3 (const T1 & param1, const T2 & param2, const T3 & param3)
			: m_param1 (param1), m_param2 (param2), m_param3 (param3)
		{
		}

		void retrieveData (T1 & param1, T2 & param2, T3 & param3)
		{
			param1 = m_param1;
			param2 = m_param2;
			param3 = m_param3;
		}
};

template <class T1, class T2, class T3, class T4> class ParameterCache_4 : public ParameterCache {
	private:
		T1 m_param1;
		T2 m_param2;
		T3 m_param3;
		T4 m_param4;
	public:
		ParameterCache_4 (const T1 & param1, const T2 & param2, const T3 & param3, const T4 & param4)
			: m_param1 (param1), m_param2 (param2), m_param3 (param3), m_param4 (param4)
		{
		}

		void retrieveData (T1 & param1, T2 & param2, T3 & param3, T4 & param4)
		{
			param1 = m_param1;
			param2 = m_param2;
			param3 = m_param3;
			param4 = m_param4;
		}
};


/*************************************************************************************************************************
 Class interface for Base 
**************************************************************************************************************************/

class IBase {
private:
	std::unique_ptr<ParameterCache> m_ParameterCache;
public:
	/**
	* IBase::~IBase - virtual destructor of IBase
	*/
	virtual ~IBase() {};

	/**
	* IBase::ReleaseBaseClassInterface - Releases ownership of a base class interface. Deletes the reference, if necessary.
	* @param[in] pIBase - The base class instance to release
	*/
	static void ReleaseBaseClassInterface(IBase* pIBase)
	{
		if (pIBase) {
			pIBase->DecRefCount();
		}
	};

	/**
	* IBase::AcquireBaseClassInterface - Acquires shared ownership of a base class interface.
	* @param[in] pIBase - The base class instance to acquire
	*/
	static void AcquireBaseClassInterface(IBase* pIBase)
	{
		if (pIBase) {
			pIBase->IncRefCount();
		}
	};


	/**
	* IBase::GetLastErrorMessage - Returns the last error registered of this class instance
	* @param[out] sErrorMessage - Message of the last error registered
	* @return Has an error been registered already
	*/
	virtual bool GetLastErrorMessage(std::string & sErrorMessage) = 0;

	/**
	* IBase::ClearErrorMessages - Clears all registered messages of this class instance
	*/
	virtual void ClearErrorMessages() = 0;

	/**
	* IBase::RegisterErrorMessage - Registers an error message with this class instance
	* @param[in] sErrorMessage - Error message to register
	*/
	virtual void RegisterErrorMessage(const std::string & sErrorMessage) = 0;

	/**
	* IBase::IncRefCount - Increases the reference count of a class instance
	*/
	virtual void IncRefCount() = 0;

	/**
	* IBase::DecRefCount - Decreases the reference count of a class instance and free releases it, if the last reference has been removed
	* @return Has the object been released
	*/
	virtual bool DecRefCount() = 0;

	/**
	* IBase::_setCache - set parameter cache of object
	*/
	void _setCache(ParameterCache * pCache)
	{
		m_ParameterCache.reset(pCache);
	}

	/**
	* IBase::_getCache - returns parameter cache of object
	*/
	ParameterCache* _getCache()
	{
		return m_ParameterCache.get();
	}

};


/**
 Definition of a shared pointer class for IBase
*/
template<class T>
class IBaseSharedPtr : public std::shared_ptr<T>
{
public:
	explicit IBaseSharedPtr(T* t = nullptr)
		: std::shared_ptr<T>(t, IBase::ReleaseBaseClassInterface)
	{
		t->IncRefCount();
	}

	// Reset function, as it also needs to properly set the deleter.
	void reset(T* t = nullptr)
	{
		std::shared_ptr<T>::reset(t, IBase::ReleaseBaseClassInterface);
	}

	// Get-function that increases the Base class's reference count
	T* getCoOwningPtr()
	{
		T* t = this->get();
		t->IncRefCount();
		return t;
	}
};


typedef IBaseSharedPtr<IBase> PIBase;


/*************************************************************************************************************************
 Class interface for Driver 
**************************************************************************************************************************/

class IDriver : public virtual IBase {
public:
	/**
	* IDriver::Configure - Configures a driver with its specific configuration data.
	* @param[in] sConfigurationString - Configuration data of driver.
	*/
	virtual void Configure(const std::string & sConfigurationString) = 0;

	/**
	* IDriver::GetName - returns the name identifier of the driver
	* @return Name of the driver.
	*/
	virtual std::string GetName() = 0;

	/**
	* IDriver::GetType - returns the type identifier of the driver
	* @return Type of the driver.
	*/
	virtual std::string GetType() = 0;

	/**
	* IDriver::GetVersion - returns the version identifiers of the driver
	* @param[out] nMajor - Major version.
	* @param[out] nMinor - Minor version.
	* @param[out] nMicro - Micro version.
	* @param[out] sBuild - Build identifier.
	*/
	virtual void GetVersion(LibMCDriver_OpenFOAM_uint32 & nMajor, LibMCDriver_OpenFOAM_uint32 & nMinor, LibMCDriver_OpenFOAM_uint32 & nMicro, std::string & sBuild) = 0;

	/**
	* IDriver::QueryParameters - Updates the driver parameters in the driver environment. Should only be called in the driver thread.
	*/
	virtual void QueryParameters() = 0;

	/**
	* IDriver::QueryParametersEx - Updates the driver parameters in the driver environment. Might be called out of thread. Implementation MUST be able to handle parallel calls.
	* @param[in] pDriverUpdateInstance - Status update instance.
	*/
	virtual void QueryParametersEx(LibMCEnv::PDriverStatusUpdateSession pDriverUpdateInstance) = 0;

};

typedef IBaseSharedPtr<IDriver> PIDriver;


/*************************************************************************************************************************
 Class interface for OpenFOAMCase 
**************************************************************************************************************************/

class IOpenFOAMCase : public virtual IBase {
public:
	/**
	* IOpenFOAMCase::GetIdentifier - Returns the identifier of the case.
	* @return Identifier string.
	*/
	virtual std::string GetIdentifier() = 0;

	/**
	* IOpenFOAMCase::CanRun - Returns if all prerequisites of the case have been set up and the case is not running yet.
	* @return Returns true if the case can run, false if it can not.
	*/
	virtual bool CanRun() = 0;

	/**
	* IOpenFOAMCase::GetStatus - Returns the current case status.
	* @return Returns the status variable.
	*/
	virtual LibMCDriver_OpenFOAM::eCaseStatus GetStatus() = 0;

	/**
	* IOpenFOAMCase::IsRunning - Returns if the case is running in the background.
	* @return Returns true if the case is currently running, false if is not running.
	*/
	virtual bool IsRunning() = 0;

	/**
	* IOpenFOAMCase::IsSuccessful - Returns if the case has finished successfully.
	* @return Returns true if the case has been computed successfully, false otherwise.
	*/
	virtual bool IsSuccessful() = 0;

	/**
	* IOpenFOAMCase::IsInError - Returns if the case has finished with an error.
	* @return Returns true if the case has not been able to finish successfully, false otherwise. If the case has not been started, also false is returned.
	*/
	virtual bool IsInError() = 0;

	/**
	* IOpenFOAMCase::SetBuild - Sets the simulation setup build.
	* @param[in] pBuild - Build instance to use.
	*/
	virtual void SetBuild(LibMCEnv::PBuild pBuild) = 0;

	/**
	* IOpenFOAMCase::HasBuild - Has a build job associated with the case.
	* @return Returns true, if the case has an associated build job.
	*/
	virtual bool HasBuild() = 0;

	/**
	* IOpenFOAMCase::GetBuildUUID - Returns UUID of the build.
	* @return Build job UUID.
	*/
	virtual std::string GetBuildUUID() = 0;

	/**
	* IOpenFOAMCase::StartComputation - Starts the computation. Fails if CanRun would return false.
	*/
	virtual void StartComputation() = 0;

	/**
	* IOpenFOAMCase::CreateOpenFOAMInputDeck - Writes the OpenFOAM input deck into a ZIP file
	* @param[in] pZIPStream - ZIP Stream writer to add the input deck to.
	*/
	virtual void CreateOpenFOAMInputDeck(LibMCEnv::PZIPStreamWriter pZIPStream) = 0;

};

typedef IBaseSharedPtr<IOpenFOAMCase> PIOpenFOAMCase;


/*************************************************************************************************************************
 Class interface for Driver_OpenFOAM 
**************************************************************************************************************************/

class IDriver_OpenFOAM : public virtual IDriver {
public:
	/**
	* IDriver_OpenFOAM::CreateCase - Creates an open foam case. Fails if a case with the same identifier already exists.
	* @param[in] sIdentifier - Identifier of the case. MUST be an alphanumeric string with _ allowed. MUST not exceed 128 characters.
	* @return FOAM Case instance.
	*/
	virtual IOpenFOAMCase * CreateCase(const std::string & sIdentifier) = 0;

	/**
	* IDriver_OpenFOAM::CaseExists - Checks if a case of a certain identifier exists.
	* @param[in] sIdentifier - Identifier of the case. MUST be an alphanumeric string with _ allowed. MUST not exceed 128 characters.
	* @return Returns true, if the case exists, false otherwise.
	*/
	virtual bool CaseExists(const std::string & sIdentifier) = 0;

	/**
	* IDriver_OpenFOAM::FindCase - Finds a case by a certain identifier. Fails if the case does not exist.
	* @param[in] sIdentifier - Identifier of the case. MUST be an alphanumeric string with _ allowed. MUST not exceed 128 characters.
	* @return FOAM Case instance.
	*/
	virtual IOpenFOAMCase * FindCase(const std::string & sIdentifier) = 0;

	/**
	* IDriver_OpenFOAM::ReleaseCase - Releases the case, frees all of its references and memory and removes the working directory from disk. Cancels any ongoing computation. Does nothing, if case does not exist.
	* @param[in] sIdentifier - Identifier of the case. MUST be an alphanumeric string with _ allowed. MUST not exceed 128 characters.
	*/
	virtual void ReleaseCase(const std::string & sIdentifier) = 0;

};

typedef IBaseSharedPtr<IDriver_OpenFOAM> PIDriver_OpenFOAM;


/*************************************************************************************************************************
 Global functions declarations
**************************************************************************************************************************/
class CWrapper {
public:
	// Injected Components
	static LibMCEnv::PWrapper sPLibMCEnvWrapper;

	/**
	* Ilibmcdriver_openfoam::GetVersion - retrieves the binary version of this library.
	* @param[out] nMajor - returns the major version of this library
	* @param[out] nMinor - returns the minor version of this library
	* @param[out] nMicro - returns the micro version of this library
	*/
	static void GetVersion(LibMCDriver_OpenFOAM_uint32 & nMajor, LibMCDriver_OpenFOAM_uint32 & nMinor, LibMCDriver_OpenFOAM_uint32 & nMicro);

	/**
	* Ilibmcdriver_openfoam::GetLastError - Returns the last error recorded on this object
	* @param[in] pInstance - Instance Handle
	* @param[out] sErrorMessage - Message of the last error
	* @return Is there a last error to query
	*/
	static bool GetLastError(IBase* pInstance, std::string & sErrorMessage);

	/**
	* Ilibmcdriver_openfoam::ReleaseInstance - Releases shared ownership of an Instance
	* @param[in] pInstance - Instance Handle
	*/
	static void ReleaseInstance(IBase* pInstance);

	/**
	* Ilibmcdriver_openfoam::AcquireInstance - Acquires shared ownership of an Instance
	* @param[in] pInstance - Instance Handle
	*/
	static void AcquireInstance(IBase* pInstance);

	/**
	* Ilibmcdriver_openfoam::CreateDriver - Creates a driver instance with a specific name.
	* @param[in] sName - Name of driver to be created.
	* @param[in] sType - Type of driver to be created.
	* @param[in] pDriverEnvironment - Environment of this driver.
	* @return New Driver instance
	*/
	static IDriver * CreateDriver(const std::string & sName, const std::string & sType, LibMCEnv::PDriverEnvironment pDriverEnvironment);

};

LibMCDriver_OpenFOAMResult LibMCDriver_OpenFOAM_GetProcAddress (const char * pProcName, void ** ppProcAddress);

} // namespace Impl
} // namespace LibMCDriver_OpenFOAM

#endif // __LIBMCDRIVER_OPENFOAM_CPPINTERFACES
